title = "ADE crypt Gitleaks Config"

[extend]
useDefault = true

[[rules]]
id = "encryption-key"
description = "Hardcoded encryption key"
regex = '''(?i)(encryption_key|encrypt_key|cipher_key)\s*=\s*["'][^"']{16,}["']'''
tags = ["key", "encryption"]

[[rules]]
id = "temp-file-pattern"
description = "Predictable temp file using PID"
regex = '''/tmp/[a-zA-Z_]+\$\$'''
tags = ["security", "temp"]

[[rules]]
id = "hardcoded-password"
description = "Hardcoded password"
regex = '''(?i)(password|passwd|pwd)\s*=\s*["'][^"']+["']'''
tags = ["password"]

[allowlist]
paths = [
    "tests/",
    "*.bats",
    ".gitleaks.toml"
]
